Regenerate Management and Recurring
Adyen/adyen-java-api-library pull request #1008
Opened 2023-04-24 11:24 UTC by jillingk

**Description**
This PR regenerates management and recurring endpoints.

2023-05-01 09:06 UTC, wboereboom requested changes

2023-05-01 09:06 UTC, wboereboom commented on src/main/java/com/adyen/model/recurring/ScheduleAccountUpdaterRequest.java
> + * The Recurring APIs allow you to manage and remove your tokens or saved payment details. Tokens should be created with validation during a payment request.  For more information, refer to our [Toke
Do we really need the full API description for every model?

2023-05-01 09:22 UTC, wboereboom approved these changes

2023-05-08 09:34 UTC, michaelpaul approved these changes

2023-05-08 09:44 UTC, merged