Update README.md
Adyen/adyen-java-api-library pull request #1014
Opened 2023-05-04 15:08 UTC by jillingk

**Description**
update endpoint versions

2023-05-05 09:16 UTC, wboereboom requested changes

2023-05-05 09:16 UTC, wboereboom commented on README.md
> +| [Checkout API](https://docs.adyen.com/api-explorer/#/CheckoutService/v69/overview)                                   | Our latest integration for accepting online payments.
```suggestion
| [Checkout API](https://docs.adyen.com/api-explorer/#/CheckoutService/v70/overview)                                   | Our latest integration for accepting online payments.                                                                                                                                                                                                                                                             | Checkout                                 | **v70**           |
```

2023-05-05 09:16 UTC, wboereboom commented on README.md
> +| [BIN lookup API](https://docs.adyen.com/api-explorer/#/BinLookup/v52/overview)                                       | The BIN Lookup API provides endpoints for retrieving information based on a gi
```suggestion
| [BIN lookup API](https://docs.adyen.com/api-explorer/#/BinLookup/v54/overview)                                       | The BIN Lookup API provides endpoints for retrieving information based on a given BIN.                                                                                                                                                                                                                            | BinLookup                                | **v54**           |
```

2023-05-08 08:50 UTC, michaelpaul approved these changes

2023-05-08 08:57 UTC, wboereboom approved these changes

2023-05-12 12:20 UTC, merged