Remove hard validation for additional and optional fields
Adyen/adyen-java-api-library pull request #1030
Opened 2023-05-15 14:55 UTC by jillingk

**Description**
Remove hard validation for additional/optional fields so that added parameters will not break live integrations. Also had to ignore the logger for oneOf fields (as that validation will fail always).

2023-05-16 07:00 UTC, wboereboom requested changes

2023-05-16 07:00 UTC, wboereboom commented on templates/libraries/okhttp-gson/pojo.mustache
> +          log.log(Level.WARNING, String.format("The field `%s` in the JSON string is not defined in the `BusinessLineInfo` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
```suggestion
          log.log(Level.WARNING, String.format("The field `%s` in the JSON string is not defined in the `{{classname}}` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
```

2023-05-16 07:01 UTC, wboereboom commented
I think this also warrants a unit test to verify new behavior

2023-05-16 12:06 UTC, jillingk commented
> I think this also warrants a unit test to verify new behavior

@wboereboom we already have tests for oneOf models, which is the main concern for this fix. In order for them to pass I needed to leave the required parameter validation (basically this is the only requirement for the oneOf models to properly deserialize I found). Afterwards I also checked that for the oneOf model deserialization the warning is supressed. Is there any other scenarios that we need to test you think?

2023-05-22 11:22 UTC, wboereboom approved these changes

2023-05-22 11:22 UTC, wboereboom approved these changes

2023-05-22 13:59 UTC, merged