Add services workflow
Adyen/adyen-java-api-library pull request #1094
Opened 2023-07-26 13:38 UTC by AlexandrosMor

**Description**
Add the services workflow for java

**Tested scenarios**
Generate the models and the services local

2023-07-26 14:15 UTC, michaelpaul requested changes

2023-07-26 14:15 UTC, michaelpaul commented on .github/workflows/service.yml
> +            Adyen/Service
```suggestion
            src/main/java/com/adyen/model
            src/main/java/com/adyen/service
```

2023-07-27 07:56 UTC, Aleffio commented on .github/workflows/service.yml
> +            src/main/java/com/adyen/model
just to understand, if this script is for both /service and /model, do we plan to remove the `models.yml` file?

2023-07-27 11:13 UTC, Aleffio approved these changes

2023-07-27 11:25 UTC, michaelpaul requested changes
Let's keep the `models.yml` workflow and introduce a separate `services.yml`. Models change more frequently and maintain compatibility, which is the opposite of how services evolve normally.

2023-07-27 13:13 UTC, michaelpaul approved these changes

2023-07-28 06:41 UTC, jillingk approved these changes

2023-07-28 07:07 UTC, merged