ITT-542 rebased on develop
Adyen/adyen-java-api-library pull request #1141
Opened 2023-10-06 09:52 UTC by jillingk

**Description**
@timon-langlotz

2023-10-16 12:42 UTC, Aleffio requested changes

2023-10-16 12:57 UTC, jillingk commented on README.md
>  ```java
Good catch!

2023-10-16 13:12 UTC, jillingk commented on README.md
>  ```java
changed the readme

2023-10-18 08:25 UTC, Aleffio approved these changes

2023-10-23 11:32 UTC, AlexandrosMor approved these changes

2023-10-23 11:38 UTC, merged