Fix Flaky Tests without New Dependencies
Adyen/adyen-java-api-library pull request #681
Opened 2022-02-07 11:58 UTC by kaiyaok2

**Description**
45 flaky tests are found using Nondex when running commands, including all tests presented in the earlier PR https://github.com/Adyen/adyen-java-api-library/pull/654. This PR fixes 3 of them without introducing new plugins / dependencies.
```mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest={test}``` 
For example, replacing `{test}` by `CheckoutTest` checks for all flaky tests in  `CheckoutTest.java`. 
All 45 flaky tests are related to JSON-format strings. 44 of them are representing JSONObject-likes and 1 of them is representing JSONArray-like. Direct comparisons between JSON-formatted strings may occasionally fail upon changes of environment (e.g. using future versions of Java), as element orders in JSONObjects/JSONArrays are not preserved. 
**Proposed Fixes**
Changes to specific test files fall into the following 3 categories:
- For assertions that include raw comparison of JSON-format strings: call my implemented helper function `assertJsonStringEquals()` instead. The function makes direct comparisons after parsing input strings with Gson's `JsonParser()` method, allowing permutation of element orders in JSONs.  
- For tests that include `jsonRequest.contains(some_JSON_string)`, add all possible permutation patterns of `some_JSON_string`
- For the test that casts JSONObject-like strings to base64 before comparison: To make the comparison deterministic, we convert the JSONObjects represented by the strings to TreeMaps (using the helper function `jsonObjectStringToTreeMap()`  before casting them to strings.

I can open a new PR fixing all the 45 flaky tests if this PR is accepted!

2022-02-23 21:34 UTC, michaelpaul requested changes
Hi @kaiyaok2, thanks for submitting your contribution! I've just noticed an issue with the new method `com.adyen.util.Util#jsonObjectStringToTreeMap`. 

The format produced by it can only be used in the tests.

2022-02-24 07:20 UTC, kaiyaok2 commented on src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
> +        json = (Util.jsonObjectStringToTreeMap(json)).toString(); // Convert the JSONObject-like string to a treemap and cast it back to string to avoid element permutation
Thanks for pointing this out! I resolved this issue by the Jackson writeValueAsString routine.

2022-02-24 13:23 UTC, michaelpaul commented
Hi @kaiyaok2, the `SaleToAcquirerData` is an important class on the library that we don't want to change to avoid breaking existing merchant applications. The new changes hide possible exceptions from the application and exposing new exceptions would lead to a breaking change in the API.

Feel free to change the test code of the library.

2022-02-24 16:45 UTC, kaiyaok2 commented
> Hi @kaiyaok2, the `SaleToAcquirerData` is an important class on the library that we don't want to change to avoid breaking existing merchant applications. The new changes hide possible exceptions from the application and exposing new exceptions would lead to a breaking change in the API.
> 
> Feel free to change the test code of the library.

Hi there, thanks for your message! I updated a commit to remove possible exceptions by using Gson instead, and hopefully this will not break the API.

Other 44 of the 45 flaky tests can be done solely with modifications to test files only. However, for base64 comparison, I believe that the test flakiness cannot be resolved(without hardcoding) unless we force `toBase64()` to work with order-deterministic inputs.

2022-02-24 22:25 UTC, michaelpaul requested changes
Checkout this another idea to deal with the base64 encoded JSON strings. In test code we can tradeoff some performance in favor of determinism.

2022-02-24 22:25 UTC, michaelpaul commented on src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
> +        return new String(Base64.encodeBase64(jsonOrdered.getBytes()));
This solution introduces some overhead by JSON encoding the data twice. 
```suggestion
        return new String(Base64.encodeBase64(json.getBytes()));
```

2022-02-24 22:25 UTC, michaelpaul commented on src/main/java/com/adyen/util/Util.java
> +             map.replace(key, jsonObjectStringToTreeMap(map.get(key).toString()));
This recursive JSON decoding will perform duplicated work on the inner objects.

2022-02-25 04:07 UTC, kaiyaok2 commented
> Checkout this another idea to deal with the base64 encoded JSON strings. In test code we can tradeoff some performance in favor of determinism.

I just updated with a commit with all proposed changes done!

Also, the other flaky tests in the repo are similar to ones in `testGsonAndJacksonSerializeNotificationRequest()` and `testPaymentsRequestWithXidAndCavv()`, and can be done smoothly with some inline changes in test files. Shall I do another commit fixing all those?

2022-02-25 14:54 UTC, michaelpaul submitted a review, later dismissed

2022-02-25 14:57 UTC, michaelpaul commented
> I just updated with a commit with all proposed changes done!
> 
> Also, the other flaky tests in the repo are similar to ones in `testGsonAndJacksonSerializeNotificationRequest()` and `testPaymentsRequestWithXidAndCavv()`, and can be done smoothly with some inline changes in test files. Shall I do another commit fixing all those?

Nice! You can update those as well if you like. :)

2022-02-26 03:06 UTC, kaiyaok2 commented
> > I just updated with a commit with all proposed changes done!
> > Also, the other flaky tests in the repo are similar to ones in `testGsonAndJacksonSerializeNotificationRequest()` and `testPaymentsRequestWithXidAndCavv()`, and can be done smoothly with some inline changes in test files. Shall I do another commit fixing all those?
> 
> Nice! You can update those as well if you like. :)

The latest commit updates all the other tests 👍

2022-02-28 07:48 UTC, AlexandrosMor approved these changes

2022-02-28 13:37 UTC, kaiyaok2 commented
Hi @michaelpaul could you please check the newest version?

2022-03-03 14:44 UTC, michaelpaul approved these changes

2022-03-04 10:09 UTC, kaiyaok2 commented
Hi @AlexandrosMor @michaelpaul,  What are the checks for coverage/coveralls? How can I ensure that these checks pass?

2022-03-16 13:49 UTC, michaelpaul commented
> Hi @AlexandrosMor @michaelpaul, What are the checks for coverage/coveralls? How can I ensure that these checks pass?

Hi @kaiyaok2, the coveralls process runs unit tests with code coverage. I believe we need to make some adjustments for this check. If the tests are passing on your machine, then you don't have anything else to do.

2022-03-16 14:49 UTC, kaiyaok2 commented
> > Hi @AlexandrosMor @michaelpaul, What are the checks for coverage/coveralls? How can I ensure that these checks pass?
> 
> Hi @kaiyaok2, the coveralls process runs unit tests with code coverage. I believe we need to make some adjustments for this check. If the tests are passing on your machine, then you don't have anything else to do.

Got it, I had all tests passing on my machine. Thanks for clarifying!

2022-03-17 13:20 UTC, merged