PW-7049: Upgrade Recurring from v49 to v68
Adyen/adyen-java-api-library pull request #830
Opened 2022-09-28 13:33 UTC by michaelpaul

**Description**

This PR upgrades the [Recurring](https://docs.adyen.com/api-explorer-beta/Recurring/68/overview) service to it's latest version **v68**.

2022-09-28 13:43 UTC, jillingk submitted a review, later dismissed

2022-09-28 16:02 UTC, wboereboom requested changes
Looks good. tiny detail in a header that might need a quick fix

2022-09-28 16:02 UTC, wboereboom commented on src/test/java/com/adyen/RecurringTest.java
> + * <p>
Why is this in the header?

2022-09-28 16:02 UTC, wboereboom commented on src/test/java/com/adyen/RecurringTest.java
> + * <p>
```suggestion
```

2022-09-29 13:49 UTC, wboereboom submitted a review, later dismissed

2022-09-30 15:29 UTC, wboereboom approved these changes

2022-10-28 12:21 UTC, merged