[PW-7256] Add Bank and Issuing Fund Transfers V3 API
Adyen/adyen-java-api-library pull request #856
Opened 2022-10-21 12:57 UTC by AlexandrosMor

**Description**

Added the models and the following endpoints:

/transactions
/transactions/{id}
/transfers

**Tested scenarios**

Added unit tests based on the open api examples

2022-10-21 13:05 UTC, michaelpaul requested changes
See my previous comment: https://github.com/Adyen/adyen-java-api-library/pull/854#discussion_r1001530658

2022-10-21 15:01 UTC, michaelpaul approved these changes

2022-10-21 15:06 UTC, wboereboom approved these changes

2022-10-24 13:59 UTC, wboereboom commented on src/main/java/com/adyen/service/Transfers.java
> +    public TransactionSearchResponse list() throws IOException, ApiException {
Maybe it is good to rename these. These endpoints are about transactions, whereas the first one is about a Tranasfer.

2022-10-28 08:41 UTC, wboereboom commented
MakeFile and Readme should also get updated

2022-11-01 14:47 UTC, wboereboom commented on src/main/java/com/adyen/service/Transfers.java
> +    public TransactionSearchResponse list() throws IOException, ApiException {
@AlexandrosMor can you look into this?

2022-11-03 07:47 UTC, merged