[PW-7051] Binlookup models
Adyen/adyen-java-api-library pull request #872
Opened 2022-11-04 11:37 UTC by AlexandrosMor

**Description**

Added the binlookup models
Update the service
**Tested scenarios**

Added the open api specs examples in unit tests

2022-11-04 11:48 UTC, wboereboom approved these changes

2022-11-04 11:49 UTC, wboereboom requested changes
Please also update README.md

2022-11-18 12:01 UTC, wboereboom approved these changes

2022-11-18 12:20 UTC, michaelpaul approved these changes

2022-11-18 12:21 UTC, merged